services:
  vuego-playground:
    build:
      context: ${PWD}
      dockerfile: docker/playground/Dockerfile
      network: host
    ports:
      - "8080:8080"
    volumes:
      - $PWD/docker/playground/cmd/vuego-playground/static:/app/examples
    environment:
      - LOG_LEVEL=info
